backend:
  name: github
  repo: DadeHubs/my-vnote # نام کاربری و نام مخزن گیت‌هاب
  branch: main # شاخه اصلی شما

  # این خطوط را بعداً با آدرس Worker خود آپدیت می‌کنیم
  base_url: https://my-vnote.pages.dev/
  auth_endpoint: /api/auth # این یک آدرس موقت است

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "پست‌ها"
    folder: "posts" # پوشه‌ای که پست‌های Markdown در آن قرار دارند
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }
      - { label: "توضیحات کوتاه", name: "description", widget: "string" }
      - { label: "محتوای اصلی", name: "body", widget: "markdown" }
